### ISSUE TITLE
Problems with pre3

### ISSUE THREAD

**Issue by quite** [nesquena/gitdocs#77]
Installing the latest prerelease 3 yesterday, I have run into some serious problems. I'm running gitdocs on updated Debian wheezy and Arch Linux systems. gitdocs pre3 takes 100% cpu and is slowly filling up my $HOME. I can't see where, but in my one and only share temporary files are continuously being created (but also removed) in .git/objects/.
I'm not touching the actual files in my share during all this.

On my Debian server, gitdocs eventually crashes after around 30 minutes, with log output as below. On the client I had to slay the hogging process before that... I tried with start -D but get nothing there.

```
I, [2014-04-04T06:30:06.729134 #21650]  INFO -- : Starting Gitdocs v0.5.0.pre3...
I, [2014-04-04T06:30:06.729963 #21650]  INFO -- : Using configuration root: '/home/quite/.gitdocs'
I, [2014-04-04T06:30:06.820999 #21650]  INFO -- : Shares: (1) #<Gitdocs::Configuration::Share id: 1, path: "/home/quite/gitdocs/depo", polling_interval: 15.0, notification: false, remote_name: "origin", branch_name: "master">
I, [2014-04-04T06:30:06.821824 #21650]  INFO -- : Starting EM loop...
I, [2014-04-04T06:30:28.477166 #21650]  INFO -- : Web server running!
E, [2014-04-04T07:02:04.864785 #21650] ERROR -- : Exception - #<Exception: inotify event queue has overflowed.> - "inotify event queue has overflowed."
E, [2014-04-04T07:02:04.898470 #21650] ERROR -- : /home/quite/.gem/ruby/1.9.1/gems/joshbuddy-guard-0.10.0/lib/vendor/linux/lib/rb-inotify/event.rb:120:in `initialize'
/home/quite/.gem/ruby/1.9.1/gems/joshbuddy-guard-0.10.0/lib/vendor/linux/lib/rb-inotify/event.rb:100:in `new'
/home/quite/.gem/ruby/1.9.1/gems/joshbuddy-guard-0.10.0/lib/vendor/linux/lib/rb-inotify/event.rb:100:in `consume'
/home/quite/.gem/ruby/1.9.1/gems/joshbuddy-guard-0.10.0/lib/vendor/linux/lib/rb-inotify/notifier.rb:272:in `read_events'
/home/quite/.gem/ruby/1.9.1/gems/joshbuddy-guard-0.10.0/lib/vendor/linux/lib/rb-inotify/notifier.rb:233:in `process'
/home/quite/.gem/ruby/1.9.1/gems/joshbuddy-guard-0.10.0/lib/guard/listeners/linux.rb:81:in `watch_change'
/home/quite/.gem/ruby/1.9.1/gems/joshbuddy-guard-0.10.0/lib/guard/listeners/linux.rb:21:in `start'
/home/quite/.gem/ruby/1.9.1/gems/gitdocs-0.5.0.pre3/lib/gitdocs/runner.rb:55:in `block in run'  
/home/quite/.gem/ruby/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:1037:in `call'
/home/quite/.gem/ruby/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:1037:in `block in spawn_threadpool'  
I, [2014-04-04T07:02:05.247147 #21650]  INFO -- : Gitdocs is terminating...goodbye
```

**Comment by acant** [comment]
@quite I was wondering if you mind if I close this issue? There are a lot of changes since pre3, so things might be resolved or at least significantly different.

**Comment by acant** [comment]
Sorry hit the wrong button. :) Waiting for a response before really closing this.
